import { NemotronProjectPlanInput } from '../schemas/projectPlan.schema';

export const templates: Record<string, Omit<NemotronProjectPlanInput, 'milestones'> & { milestones: Array<any> }> = {
  'saas_app': {
    executiveSummary: 'Predefined enterprise SaaS application blueprint featuring multi-tenancy, billing, authentication, and a responsive analytics dashboard.',
    productVision: 'To provide a robust, scalable SaaS framework that enables secure tenant onboarding, billing telemetry, and user management.',
    functionalRequirements: [
      'Multi-tenant workspace isolation.',
      'Subscription billing integration with Stripe.',
      'User role permission levels (Admin, Member, Viewer).',
      'Unified analytics dashboard showing usage metrics.',
    ],
    nonFunctionalRequirements: [
      'Sub-second dashboard paint times.',
      'Data isolation at the database schema level.',
      '99.95% API service availability.',
    ],
    systemArchitecture: 'React frontend, Express Node.js API server, PostgreSQL database, Prisma ORM, and Redis for session cache.',
    databaseDesign: 'Tenants, Users, Workspaces, and Subscription schemas with cross-relation foreign keys and indexes on tenantId.',
    apiDesign: 'REST endpoints including POST /auth/register, POST /billing/subscribe, GET /workspace/metrics, and PUT /tenant/settings.',
    milestones: [
      {
        title: 'Requirements & Wireframes',
        description: 'Establish SaaS product definitions, tenant data schemas, and design visual UI wireframes.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['Database schemas approved', 'Visual UX mockups signed off'],
        deliverables: ['Database schema diagrams', 'UX Figma link'],
        percentage: 10,
        releaseConditions: ['Schema and designs committed to repo documentation folder.'],
        githubAuditRequirements: ['docs/architecture.md', 'docs/schema.sql'],
      },
      {
        title: 'Frontend Development',
        description: 'Implement responsive React frontend screens, including login, dashboard, and settings.',
        estimatedDays: 8,
        dependencies: ['Requirements & Wireframes'],
        acceptanceCriteria: ['All screens render correctly on mobile/desktop', 'State management functions properly'],
        deliverables: ['React component library', 'State store configurations'],
        percentage: 25,
        releaseConditions: ['Frontend bundle builds without errors', 'Component test suite passing'],
        githubAuditRequirements: ['src/components/Dashboard.tsx', 'src/store/authStore.ts'],
      },
      {
        title: 'Backend APIs & Database',
        description: 'Code the Express API routes, controller functions, and setup database migrations.',
        estimatedDays: 7,
        dependencies: ['Requirements & Wireframes'],
        acceptanceCriteria: ['API endpoints respond with correct status codes', 'Prisma database connection is functional'],
        deliverables: ['API controller files', 'Prisma migration history log'],
        percentage: 20,
        releaseConditions: ['API unit tests pass', 'Database migrations run successfully'],
        githubAuditRequirements: ['server/src/controllers/tenant.controller.ts', 'prisma/schema.prisma'],
      },
      {
        title: 'Authentication & Payments',
        description: 'Integrate JWT authentication middleware, tenant signup validation, and Stripe webhook payment listeners.',
        estimatedDays: 6,
        dependencies: ['Frontend Development', 'Backend APIs & Database'],
        acceptanceCriteria: ['JWT tokens expire correctly', 'Stripe checkout webhooks record successful charges in database'],
        deliverables: ['JWT middleware', 'Stripe webhook receiver routes'],
        percentage: 20,
        releaseConditions: ['Payments integration runs in Stripe sandbox mode', 'Secure endpoints block unauthorized users'],
        githubAuditRequirements: ['server/src/middleware/auth.ts', 'server/src/services/stripe.ts'],
      },
      {
        title: 'Testing & Deployment',
        description: 'Write integration test cases, Dockerize the system, and deploy to staging environment.',
        estimatedDays: 5,
        dependencies: ['Authentication & Payments'],
        acceptanceCriteria: ['Overall test coverage > 75%', 'Container builds successfully and deploys on Railway/AWS'],
        deliverables: ['Docker configurations', 'Staging deployment URL link'],
        percentage: 15,
        releaseConditions: ['Staging deployment is live', 'All E2E test runs are passing in CI pipeline'],
        githubAuditRequirements: ['Dockerfile', 'docker-compose.yml', 'tests/integration.test.ts'],
      },
      {
        title: 'Final Audit & Release',
        description: 'Complete final security audits, verification of requirements, and hand over the codebase.',
        estimatedDays: 3,
        dependencies: ['Testing & Deployment'],
        acceptanceCriteria: ['Zero critical vulnerabilities in dependencies', 'Code meets all acceptance criteria'],
        deliverables: ['Final audit report', 'Production source code release tag'],
        percentage: 10,
        releaseConditions: ['Audit reports show success', 'Escrow release request approved'],
        githubAuditRequirements: ['docs/release_notes.md', 'audit-report.json'],
      },
    ],
    tasks: [
      {
        title: 'Initialize Project Repository',
        description: 'Set up folder structures, ESLint rules, and TypeScript compilation targets.',
        estimatedHours: 4,
        priority: 'low',
        acceptanceCriteria: ['Repo compiles locally', 'No lint errors'],
        githubAuditRequirements: ['package.json', 'tsconfig.json'],
      },
      {
        title: 'Write User Schema and Mongoose/Prisma Models',
        description: 'Create Database tables with appropriate foreign keys and indices.',
        estimatedHours: 8,
        priority: 'high',
        acceptanceCriteria: ['Database migrations compile'],
        githubAuditRequirements: ['prisma/schema.prisma'],
      },
      {
        title: 'Implement JWT Token Filters',
        description: 'Code the middleware interceptor securing tenant APIs.',
        estimatedHours: 6,
        priority: 'high',
        acceptanceCriteria: ['Protects private routes', 'Permits public logins'],
        githubAuditRequirements: ['server/src/middleware/auth.ts'],
      },
    ],
    acceptanceCriteria: ['System runs securely', 'Multi-tenant boundaries are strict'],
    dependencies: ['Stripe developer account', 'PostgreSQL instance'],
    riskAnalysis: [
      {
        description: 'Stripe API token expiration.',
        severity: 'medium',
        mitigation: 'Set up auto-renewal alerts and health telemetry monitoring.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 25,
      realisticDays: 33,
      conservativeDays: 45,
      summary: 'Requires approximately 5 weeks of engineering time spanning 6 milestones.',
    },
    deploymentStrategy: 'Multi-stage Docker container deployed to Railway, connected to external PostgreSQL.',
    testingStrategy: 'Unit tests using Vitest, integration testing, and GitHub Actions CI gate checks.',
  },
  'fintech_app': {
    executiveSummary: 'Predefined compliant digital wallet framework featuring transaction logging, KYC workflows, bank ledger transfers, and multi-sig security.',
    productVision: 'To offer a secure fintech platform with cryptographically signed ledgers, instant transfers, and automated audit trails.',
    functionalRequirements: [
      'KYC registration validation.',
      'Double-entry transaction ledger.',
      'Cardano/USD gateway integration.',
      'Biometric authentication verification.',
    ],
    nonFunctionalRequirements: [
      'Transaction integrity guarantees (ACID).',
      'Encrypted financial data fields.',
      'Compliance validation checks.',
    ],
    systemArchitecture: 'Node.js wallet backend, secure HSM token signing server, Redis lock management, PostgreSQL database.',
    databaseDesign: 'Wallets, Transactions, KYCDocuments, and Audits tables with serial lock locks.',
    apiDesign: 'REST API endpoints including POST /wallet/transfer, GET /wallet/balance, and POST /kyc/submit.',
    milestones: [
      {
        title: 'Ledger Design & DB Schema',
        description: 'Configure audit-resilient double-entry tables with balance locks.',
        estimatedDays: 5,
        dependencies: [],
        acceptanceCriteria: ['Zero balance mutation anomalies', 'Indices exist on transaction hashes'],
        deliverables: ['Database schemas', 'Double-entry test scripts'],
        percentage: 15,
        releaseConditions: ['Database scripts committed and checked.'],
        githubAuditRequirements: ['db/migrations/ledger.sql', 'src/ledger.ts'],
      },
      {
        title: 'KYC & User Authentication',
        description: 'Build user signup pipelines with ID upload encryption.',
        estimatedDays: 6,
        dependencies: ['Ledger Design & DB Schema'],
        acceptanceCriteria: ['Private details stored encrypted', 'Unauthenticated calls are blocked'],
        deliverables: ['Auth routes', 'KYC image processor'],
        percentage: 20,
        releaseConditions: ['KYC integration flows pass mock tests.'],
        githubAuditRequirements: ['src/routes/auth.ts', 'src/services/kyc.ts'],
      },
      {
        title: 'Wallet Balances & Transfers',
        description: 'Implement balance checks, transfer ledger logic, and fee models.',
        estimatedDays: 8,
        dependencies: ['Ledger Design & DB Schema'],
        acceptanceCriteria: ['Simultaneous transfers do not cause race conditions', 'Fees calculated accurately'],
        deliverables: ['Transfer APIs', 'Mutex locks implementations'],
        percentage: 30,
        releaseConditions: ['Transfer logic passes concurrency stress tests.'],
        githubAuditRequirements: ['src/services/wallet.ts', 'src/controllers/transfer.ts'],
      },
      {
        title: 'Bank Integration Gateway',
        description: 'Integrate external mock payout systems or Cardano blockchain gateway API.',
        estimatedDays: 7,
        dependencies: ['Wallet Balances & Transfers'],
        acceptanceCriteria: ['Withdrawal logs record external transaction hashes'],
        deliverables: ['Gateway connectors', 'Sync scheduler'],
        percentage: 20,
        releaseConditions: ['Integration passes mock tests.'],
        githubAuditRequirements: ['src/services/cardano.ts', 'src/services/bank.ts'],
      },
      {
        title: 'Compliance & Audits Audit',
        description: 'Perform ledger audits, dependency checks, and verify blockchain release gates.',
        estimatedDays: 4,
        dependencies: ['Bank Integration Gateway'],
        acceptanceCriteria: ['All audit verification tests pass', 'Financial records map accurately'],
        deliverables: ['Ledger reconcile script', 'Audit report'],
        percentage: 15,
        releaseConditions: ['Ledger is verified and fully balanced.'],
        githubAuditRequirements: ['src/tests/audit.test.ts', 'src/services/reconciler.ts'],
      },
    ],
    tasks: [
      {
        title: 'Implement Database Transactions Locking',
        description: 'Write PostgreSQL serializable transaction wrappers for bank ledger safety.',
        estimatedHours: 10,
        priority: 'high',
        acceptanceCriteria: ['Transaction isolation tested successfully'],
        githubAuditRequirements: ['src/services/wallet.ts'],
      },
    ],
    acceptanceCriteria: ['Zero accounting discrepancies allowed', 'KYC validation works'],
    dependencies: ['PostgreSQL DB', 'HSM Signer access'],
    riskAnalysis: [
      {
        description: 'Concurrent transaction race conditions.',
        severity: 'critical',
        mitigation: 'Implement Redis distributed lock structures for account balances.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 20,
      realisticDays: 30,
      conservativeDays: 40,
      summary: 'Requires approximately 4 weeks of engineering time across 5 milestones.',
    },
    deploymentStrategy: 'Dockerized server on GCP Cloud Run with strict VPC firewall rules.',
    testingStrategy: 'ACID transaction test scripts, unit tests, and full trace reconciles.',
  },
  'ai_saas': {
    executiveSummary: 'Predefined AI agent integration platform blueprint featuring token count logs, prompt templates, asynchronous completions queue, and model routing.',
    productVision: 'To offer a stable, high-throughput AI SaaS builder framework that manages OpenAI/NVIDIA API pipelines.',
    functionalRequirements: [
      'Prompt template configuration.',
      'Asynchronous task worker queues.',
      'API token usage monitoring.',
      'Fallback model routing rules.',
    ],
    nonFunctionalRequirements: [
      'Resilient retry handlers for API rate limits.',
      'Secure credential encryption.',
      'Optimized token processing latency.',
    ],
    systemArchitecture: 'Next.js frontend, Python FastAPI AI runner, BullMQ task manager, Redis cache, MongoDB.',
    databaseDesign: 'Prompts, Completions, TokenLogs, and APIKeys collections.',
    apiDesign: 'Endpoints including POST /ai/complete, GET /analytics/tokens, and POST /prompts/save.',
    milestones: [
      {
        title: 'FastAPI & Schema Scaffolding',
        description: 'Initialize AI runner API server with Zod/Pydantic schemas.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['FastAPI server runs locally', 'Validation schemas pass correctly'],
        deliverables: ['API project folders', 'Pydantic model files'],
        percentage: 15,
        releaseConditions: ['FastAPI project builds successfully.'],
        githubAuditRequirements: ['api/main.py', 'api/schemas.py'],
      },
      {
        title: 'Worker Queue & Prompt Builder',
        description: 'Implement BullMQ asynchronous tasks and template compiler.',
        estimatedDays: 6,
        dependencies: ['FastAPI & Schema Scaffolding'],
        acceptanceCriteria: ['Asynchronous workers process completions', 'Variables injected correctly into prompt templates'],
        deliverables: ['Queue configurations', 'Template compiler controller'],
        percentage: 25,
        releaseConditions: ['Task workers run and connect to Redis.'],
        githubAuditRequirements: ['src/queues/aiWorker.ts', 'src/services/promptTemplate.ts'],
      },
      {
        title: 'NVIDIA/OpenAI Integrations',
        description: 'Integrate remote completions endpoint with error retry handlers.',
        estimatedDays: 7,
        dependencies: ['Worker Queue & Prompt Builder'],
        acceptanceCriteria: ['Completions fetched correctly', 'Fallback model called when main model times out'],
        deliverables: ['API wrappers', 'Fallback routes controllers'],
        percentage: 30,
        releaseConditions: ['Integration tests pass for completions.'],
        githubAuditRequirements: ['src/services/aiClient.ts', 'src/services/fallbackRouter.ts'],
      },
      {
        title: 'Usage Logs & Settings Dashboard',
        description: 'Track token usage per user and dashboard visualization.',
        estimatedDays: 8,
        dependencies: ['NVIDIA/OpenAI Integrations'],
        acceptanceCriteria: ['Token counts recorded correctly', 'Dashboard charts render data'],
        deliverables: ['Token logs middleware', 'React charts UI components'],
        percentage: 20,
        releaseConditions: ['Billing usage limits block requests when quota is exceeded.'],
        githubAuditRequirements: ['src/middleware/tokenLogger.ts', 'src/components/QuotaGauge.tsx'],
      },
      {
        title: 'Final Audit & Deploy',
        description: 'Complete API token security checks and Docker deployments.',
        estimatedDays: 5,
        dependencies: ['Usage Logs & Settings Dashboard'],
        acceptanceCriteria: ['Zero plain-text API secrets committed', 'Staging deployment runs'],
        deliverables: ['Production Dockerfile', 'Audit verification log'],
        percentage: 10,
        releaseConditions: ['Deployment live and verified.'],
        githubAuditRequirements: ['Dockerfile', 'tests/security.test.ts'],
      },
    ],
    tasks: [
      {
        title: 'Implement Prompt Variable Sanitization',
        description: 'Write filters to prevent prompt injection inside user inputs.',
        estimatedHours: 6,
        priority: 'high',
        acceptanceCriteria: ['Malicious commands stripped out'],
        githubAuditRequirements: ['src/services/promptTemplate.ts'],
      },
    ],
    acceptanceCriteria: ['AI completions process asynchronously', 'Token metrics logged'],
    dependencies: ['NVIDIA integrate keys', 'Redis server'],
    riskAnalysis: [
      {
        description: 'AI model timeout or rate limits.',
        severity: 'high',
        mitigation: 'Implement exponential backoff retries and fallback models routing.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 22,
      realisticDays: 30,
      conservativeDays: 42,
      summary: 'Requires approximately 4 weeks of engineering time across 5 milestones.',
    },
    deploymentStrategy: 'Multi-container Docker setup deployed to AWS ECS.',
    testingStrategy: 'Vitest tests and completions mock suites.',
  },
  'marketplace': {
    executiveSummary: 'Predefined multi-vendor marketplace template including vendor onboarding, product catalogs, shopping checkout, and split escrow payouts.',
    productVision: 'To deliver a multi-vendor commerce platform with seller dashboards, buyer storefronts, and secure payment splits.',
    functionalRequirements: [
      'Vendor KYC registration.',
      'Unified product inventory catalog.',
      'Split payment checkout integration.',
      'Order fulfillment status updates.',
    ],
    nonFunctionalRequirements: [
      'Responsive listing search filters.',
      'Strict database isolation for seller stores.',
      'High-availability transactional notifications.',
    ],
    systemArchitecture: 'Next.js web client, Node.js API gateway, PostgreSQL database, Sequelize ORM.',
    databaseDesign: 'Sellers, Products, Orders, OrderItems, and PayoutSplits schemas.',
    apiDesign: 'Endpoints including GET /products, POST /orders/checkout, and POST /seller/onboard.',
    milestones: [
      {
        title: 'Onboarding & Catalogs',
        description: 'Build vendor signup pages and product listing forms.',
        estimatedDays: 5,
        dependencies: [],
        acceptanceCriteria: ['Seller onboarding creates records', 'Product forms store images correctly'],
        deliverables: ['Seller forms components', 'Product catalog tables'],
        percentage: 20,
        releaseConditions: ['Catalog schemas deployed.'],
        githubAuditRequirements: ['src/controllers/seller.ts', 'src/models/Product.ts'],
      },
      {
        title: 'Marketplace Front Store',
        description: 'Implement product search, category filters, and product details views.',
        estimatedDays: 7,
        dependencies: ['Onboarding & Catalogs'],
        acceptanceCriteria: ['Search filters return correct results', 'Products render dynamically'],
        deliverables: ['Search page component', 'Product card visual widgets'],
        percentage: 20,
        releaseConditions: ['Storefront builds successfully.'],
        githubAuditRequirements: ['src/components/ProductCard.tsx', 'src/store/catalogSlice.ts'],
      },
      {
        title: 'Checkout & Cart Engine',
        description: 'Develop shopping cart logic and payment gateways splits integrations.',
        estimatedDays: 8,
        dependencies: ['Marketplace Front Store'],
        acceptanceCriteria: ['Cart calculates taxes and totals', 'Payment gateway processes correct splits'],
        deliverables: ['Cart controllers', 'Split payment integration helper'],
        percentage: 30,
        releaseConditions: ['Checkout completes in sandbox.'],
        githubAuditRequirements: ['src/services/paymentSplit.ts', 'src/controllers/order.ts'],
      },
      {
        title: 'Sellers Payout center',
        description: 'Create seller revenue analytics tables and withdrawal tools.',
        estimatedDays: 6,
        dependencies: ['Checkout & Cart Engine'],
        acceptanceCriteria: ['Sellers see accurate pending payouts', 'Request payout decreases balance'],
        deliverables: ['Seller balance sheets', 'Payout APIs'],
        percentage: 20,
        releaseConditions: ['Seller dashboard verified.'],
        githubAuditRequirements: ['src/controllers/payout.ts', 'src/components/SellerBalance.tsx'],
      },
      {
        title: 'Testing & Staging Launch',
        description: 'Verify flow integration, write unit tests, and deploy container.',
        estimatedDays: 4,
        dependencies: ['Sellers Payout center'],
        acceptanceCriteria: ['All tests pass', 'Staging deployment runs without errors'],
        deliverables: ['Testing configurations', 'Staging deploy URL'],
        percentage: 10,
        releaseConditions: ['Staging deployment live.'],
        githubAuditRequirements: ['tests/checkout.test.ts', 'Dockerfile'],
      },
    ],
    tasks: [
      {
        title: 'Build Split Payment Logic',
        description: 'Calculate and route processing fees and vendor split payouts dynamically.',
        estimatedHours: 8,
        priority: 'high',
        acceptanceCriteria: ['Splits sum to exact total price'],
        githubAuditRequirements: ['src/services/paymentSplit.ts'],
      },
    ],
    acceptanceCriteria: ['Buyers can checkout', 'Sellers receive split payouts'],
    dependencies: ['PostgreSQL Database', 'Payment Processor Gateway account'],
    riskAnalysis: [
      {
        description: 'Incomplete seller onboarding during checkout.',
        severity: 'medium',
        mitigation: 'Implement cart verification checks before processing payouts.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 24,
      realisticDays: 30,
      conservativeDays: 40,
      summary: 'Requires approximately 4 weeks of engineering time across 5 milestones.',
    },
    deploymentStrategy: 'Dockerized web and API services deployed on Railway.',
    testingStrategy: 'Integration tests for checkout flows, unit tests for fees calculations.',
  },
  'ecommerce_platform': {
    executiveSummary: 'Predefined e-commerce platform template with product catalog, cart flows, Stripe checkout, shipping updates, and email notifications.',
    productVision: 'To offer a feature-rich, optimized e-commerce engine with inventory management and secure transactions.',
    functionalRequirements: [
      'Customer catalog and checkout.',
      'Stripe payments checkout integration.',
      'Inventory count tracking.',
      'Automated email notifications.',
    ],
    nonFunctionalRequirements: [
      'SEO-optimized product routes.',
      'Sub-2s page loads.',
      'Secure customer sessions.',
    ],
    systemArchitecture: 'Astro/Next.js frontend, Node.js API, PostgreSQL database, Sequelize ORM.',
    databaseDesign: 'Products, Inventory, Orders, and Customers tables with foreign relations.',
    apiDesign: 'Endpoints including GET /products, POST /cart/checkout, and POST /inventory/sync.',
    milestones: [
      {
        title: 'DB Schema & Product Catalog',
        description: 'Define product inventory tables and populate mock data.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['Catalog displays correct stock levels', 'Mongoose/Sequelize schemas approved'],
        deliverables: ['Database schemas file', 'Mock seed script'],
        percentage: 15,
        releaseConditions: ['Database seed verified.'],
        githubAuditRequirements: ['db/schema.sql', 'db/seeds.sql'],
      },
      {
        title: 'Storefront & Shop Screens',
        description: 'Design shop pages, product list, search filters, and cart.',
        estimatedDays: 6,
        dependencies: ['DB Schema & Product Catalog'],
        acceptanceCriteria: ['Product filters update list', 'Cart stores items accurately'],
        deliverables: ['Storefront components', 'Cart context stores'],
        percentage: 25,
        releaseConditions: ['Storefront compiles successfully.'],
        githubAuditRequirements: ['src/pages/index.astro', 'src/components/Cart.tsx'],
      },
      {
        title: 'Payment Gateway Setup',
        description: 'Integrate Stripe API checkout page and webhooks receiver.',
        estimatedDays: 6,
        dependencies: ['Storefront & Shop Screens'],
        acceptanceCriteria: ['Stripe redirect succeeds', 'Webhook processes payment confirmation'],
        deliverables: ['Stripe router controller', 'Webhook webhook controller'],
        percentage: 25,
        releaseConditions: ['Sandbox payment flow functional.'],
        githubAuditRequirements: ['src/controllers/stripe.ts', 'src/routes/webhooks.ts'],
      },
      {
        title: 'Order Tracking & Emails',
        description: 'Create order status history, shipping details, and SendGrid mailers.',
        estimatedDays: 5,
        dependencies: ['Payment Gateway Setup'],
        acceptanceCriteria: ['Emails sent on order creation', 'Status changes logged correctly'],
        deliverables: ['Email templates', 'Order status manager services'],
        percentage: 20,
        releaseConditions: ['Mailers working in sandboxed environment.'],
        githubAuditRequirements: ['src/services/mailer.ts', 'src/services/orderTracker.ts'],
      },
      {
        title: 'E2E Testing & Launch',
        description: 'Test cart checkout integration, deploy staging docker container.',
        estimatedDays: 4,
        dependencies: ['Order Tracking & Emails'],
        acceptanceCriteria: ['All tests pass successfully', 'Staging deployment runs without errors'],
        deliverables: ['Staging deployment URL', 'Test report'],
        percentage: 15,
        releaseConditions: ['Staging deployment verified.'],
        githubAuditRequirements: ['tests/e2e/checkout.spec.ts', 'Dockerfile'],
      },
    ],
    tasks: [
      {
        title: 'Implement Inventory Lock',
        description: 'Write database transactions that lock inventory levels during checkout to prevent double buying.',
        estimatedHours: 8,
        priority: 'high',
        acceptanceCriteria: ['Double buying prevented during high concurrency tests'],
        githubAuditRequirements: ['src/services/inventory.ts'],
      },
    ],
    acceptanceCriteria: ['Checkout processes Stripe payments', 'Inventory levels auto-sync'],
    dependencies: ['PostgreSQL DB', 'Stripe Developer Account'],
    riskAnalysis: [
      {
        description: 'Out of stock items ordered during checkout.',
        severity: 'high',
        mitigation: 'Enforce database serializable isolation on inventory locks.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 20,
      realisticDays: 25,
      conservativeDays: 35,
      summary: 'Requires approximately 3.5 weeks of engineering time across 5 milestones.',
    },
    deploymentStrategy: 'Dockerized server deployed to Railway container platform.',
    testingStrategy: 'Unit tests using Jest, E2E tests using Playwright.',
  },
  'mobile_app': {
    executiveSummary: 'Predefined mobile application template built with Flutter/React Native, featuring local SQLite database, secure keychain storage, and REST API integration.',
    productVision: 'To deliver a premium, high-performance mobile application with offline capabilities and native API integrations.',
    functionalRequirements: [
      'Responsive visual widget screens.',
      'Secure local user authentication state.',
      'REST API client integration.',
      'Offline data synchronization.',
    ],
    nonFunctionalRequirements: [
      'Fluid 60FPS animations.',
      'Keychain encryption for auth tokens.',
      'Minimal bundle compile size.',
    ],
    systemArchitecture: 'Flutter framework, Riverpod state manager, SQLite database, secure storage keychains.',
    databaseDesign: 'Local cache sqlite schemas for user details and transaction history.',
    apiDesign: 'Client-side endpoints wrapper mapping to remote REST server endpoints.',
    milestones: [
      {
        title: 'Project Scaffold & Layouts',
        description: 'Set up Flutter project structures, themes, and onboarding views.',
        estimatedDays: 5,
        dependencies: [],
        acceptanceCriteria: ['App compiles on simulator', 'Mock theme layouts fit mobile dimensions'],
        deliverables: ['Project structure template', 'Visual onboarding pages'],
        percentage: 20,
        releaseConditions: ['Flutter code compiles without errors.'],
        githubAuditRequirements: ['pubspec.yaml', 'lib/main.dart'],
      },
      {
        title: 'Authentication & Key Store',
        description: 'Implement login screen and write tokens to secure storage keychains.',
        estimatedDays: 6,
        dependencies: ['Project Scaffold & Layouts'],
        acceptanceCriteria: ['Tokens persist after app restarts', 'Private routes require auth key'],
        deliverables: ['Login widgets', 'Keychain storage wrappers'],
        percentage: 25,
        releaseConditions: ['Secure storage flows pass unit tests.'],
        githubAuditRequirements: ['lib/features/auth/login_screen.dart', 'lib/core/storage.dart'],
      },
      {
        title: 'API Services Integration',
        description: 'Develop network client, handling API calls, and serialize responses.',
        estimatedDays: 8,
        dependencies: ['Authentication & Key Store'],
        acceptanceCriteria: ['API responses serialize to models correctly', 'Retry rules apply for network failures'],
        deliverables: ['REST client wrapper', 'Domain data models'],
        percentage: 30,
        releaseConditions: ['API trace works in debug console.'],
        githubAuditRequirements: ['lib/core/api_client.dart', 'lib/models/transaction.dart'],
      },
      {
        title: 'Offline Sync & DB Cache',
        description: 'Integrate SQLite tables caching recent API results for offline usage.',
        estimatedDays: 7,
        dependencies: ['API Services Integration'],
        acceptanceCriteria: ['Offline screens render cache', 'App syncs database records on reconnect'],
        deliverables: ['SQLite model handlers', 'Network connectivity checkers'],
        percentage: 25,
        releaseConditions: ['Cache reconciles successfully without manual overrides.'],
        githubAuditRequirements: ['lib/core/sqlite_db.dart', 'lib/services/sync_worker.dart'],
      },
    ],
    tasks: [
      {
        title: 'Secure Keychain Storage Wrapper',
        description: 'Write utility functions to encrypt and save auth tokens to device keychain.',
        estimatedHours: 6,
        priority: 'high',
        acceptanceCriteria: ['Keys successfully written/retrieved securely'],
        githubAuditRequirements: ['lib/core/storage.dart'],
      },
    ],
    acceptanceCriteria: ['Mobile client runs natively', 'Offline data caching functional'],
    dependencies: ['Flutter SDK installed', 'Staging API server'],
    riskAnalysis: [
      {
        description: 'Local sqlite cache out of sync with backend database.',
        severity: 'medium',
        mitigation: 'Implement sync timestamp stamps checking during app launches.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 22,
      realisticDays: 26,
      conservativeDays: 36,
      summary: 'Requires approximately 4 weeks of engineering time across 4 milestones.',
    },
    deploymentStrategy: 'Android APK build for staging validation, iOS TestFlight distribution.',
    testingStrategy: 'Unit tests using flutter_test, widget testing for page components.',
  },
  'crm_system': {
    executiveSummary: 'Predefined CRM template featuring contact profiles, lead tracking pipeline, activity dashboards, and automated email reminders.',
    productVision: 'To offer a productive CRM management engine with activity logs and automated workflows.',
    functionalRequirements: [
      'Contact management profiles database.',
      'Lead tracking pipeline phases.',
      'Activity timeline history.',
      'Automated email reminders scheduler.',
    ],
    nonFunctionalRequirements: [
      'Indices on contact search fields.',
      'Scalable database tables.',
      'Secure access permissions controls.',
    ],
    systemArchitecture: 'React frontend, Express API server, PostgreSQL database, Sequelize ORM, and node-cron scheduler.',
    databaseDesign: 'Contacts, Leads, Activities, and Users schemas.',
    apiDesign: 'Endpoints including GET /contacts, POST /leads/transition, and GET /dashboard/pipeline.',
    milestones: [
      {
        title: 'DB Schema & Lead Models',
        description: 'Define relational PostgreSQL tables for contacts and leads.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['Relational schemas approved', 'Database migrations compile'],
        deliverables: ['SQL schema scripts', 'Sequelize model configurations'],
        percentage: 15,
        releaseConditions: ['Migrations committed and tested.'],
        githubAuditRequirements: ['src/models/Lead.ts', 'migrations/crm_init.js'],
      },
      {
        title: 'CRM Pipeline UI Layout',
        description: 'Implement Kanban drag-and-drop pipeline for lead phases.',
        estimatedDays: 6,
        dependencies: ['DB Schema & Lead Models'],
        acceptanceCriteria: ['Leads drag-and-drop transitions phases', 'State store updates successfully'],
        deliverables: ['Kanban UI components', 'Drag-and-drop controllers'],
        percentage: 25,
        releaseConditions: ['Kanban dashboard builds without errors.'],
        githubAuditRequirements: ['src/components/Kanban.tsx', 'src/store/leadSlice.ts'],
      },
      {
        title: 'Activity Logs & Details API',
        description: 'Build backend endpoints updating activity records and timelines.',
        estimatedDays: 7,
        dependencies: ['CRM Pipeline UI Layout'],
        acceptanceCriteria: ['Timeline lists notes and edits correctly', 'APIs return nested association details'],
        deliverables: ['Timeline API routes', 'Association controllers'],
        percentage: 30,
        releaseConditions: ['API integration tests pass.'],
        githubAuditRequirements: ['src/controllers/activity.ts', 'src/routes/activity.ts'],
      },
      {
        title: 'Cron Scheduler & Emails',
        description: 'Create cron jobs generating reminder emails for open leads.',
        estimatedDays: 5,
        dependencies: ['Activity Logs & Details API'],
        acceptanceCriteria: ['Cron executes at set intervals', 'Emails send with contact variables'],
        deliverables: ['Cron scheduler service', 'SendGrid connector scripts'],
        percentage: 20,
        releaseConditions: ['Cron tasks trigger without freezing backend thread.'],
        githubAuditRequirements: ['src/services/cron.ts', 'src/services/mailer.ts'],
      },
      {
        title: 'Final Audit & Deploy',
        description: 'Complete security scans, test suite runs, and staging docker configuration.',
        estimatedDays: 4,
        dependencies: ['Cron Scheduler & Emails'],
        acceptanceCriteria: ['Tests pass successfully', 'Staging deployment runs without errors'],
        deliverables: ['Staging deployment link', 'Audit logs'],
        percentage: 10,
        releaseConditions: ['Deployment live and verified.'],
        githubAuditRequirements: ['tests/pipeline.test.ts', 'Dockerfile'],
      },
    ],
    tasks: [
      {
        title: 'Develop Cron Job Reminders',
        description: 'Write node-cron task handlers querying inactive leads and sending notification triggers.',
        estimatedHours: 8,
        priority: 'medium',
        acceptanceCriteria: ['Cron execution verified in server logs'],
        githubAuditRequirements: ['src/services/cron.ts'],
      },
    ],
    acceptanceCriteria: ['Lead pipeline functional', 'Reminders triggered successfully'],
    dependencies: ['PostgreSQL DB', 'SMTP Server configuration'],
    riskAnalysis: [
      {
        description: 'Cron scheduler overlaps on long queries.',
        severity: 'low',
        mitigation: 'Implement concurrency locks on cron execution instances.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 20,
      realisticDays: 26,
      conservativeDays: 36,
      summary: 'Requires approximately 4 weeks of engineering time across 5 milestones.',
    },
    deploymentStrategy: 'Dockerized node server deployed to Railway Cloud.',
    testingStrategy: 'Unit tests using Mocha, scheduler integration validation.',
  },
  'developer_tool': {
    executiveSummary: 'Predefined developer CLI tool template including argument parser, config management, REST API wrapper, and package exporter.',
    productVision: 'To deliver an optimized, lightweight developer tool with robust console output and package formats.',
    functionalRequirements: [
      'Command CLI argument parsing.',
      'Local configuration file manager.',
      'Remote REST service synchronization.',
      'Structured text outputs (JSON/Table).',
    ],
    nonFunctionalRequirements: [
      'Fast startup runtime (<50ms).',
      'Minimal compilation bundle footprint.',
      'Secure local API credential storage.',
    ],
    systemArchitecture: 'Go CLI application / TypeScript Node bin, communicating with staging API servers.',
    databaseDesign: 'Local user configuration folder files (JSON/YAML format).',
    apiDesign: 'Local command mappings and REST client sync functions.',
    milestones: [
      {
        title: 'CLI Scaffolding & Parsers',
        description: 'Initialize tool CLI framework and command parser logic.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['Commands parse flags correctly', 'Help manual displays on empty inputs'],
        deliverables: ['CLI main runner', 'Command flag definitions'],
        percentage: 25,
        releaseConditions: ['Executable runs locally.'],
        githubAuditRequirements: ['src/index.ts', 'src/cli.ts'],
      },
      {
        title: 'Local Configs File Manager',
        description: 'Implement system folders reading/writing configurations.',
        estimatedDays: 5,
        dependencies: ['CLI Scaffolding & Parsers'],
        acceptanceCriteria: ['User configurations read/write securely', 'Config values validate dynamically'],
        deliverables: ['Config service controllers', 'Config schema files'],
        percentage: 25,
        releaseConditions: ['Local folders permissions verified.'],
        githubAuditRequirements: ['src/config.ts', 'src/utils.ts'],
      },
      {
        title: 'REST API Sync Services',
        description: 'Develop sync clients connecting local tool to remote server APIs.',
        estimatedDays: 6,
        dependencies: ['Local Configs File Manager'],
        acceptanceCriteria: ['REST payload syncs to remote DB', 'HTTP error status logs output cleanly to terminal'],
        deliverables: ['REST API connectors', 'Error log parsers'],
        percentage: 30,
        releaseConditions: ['API sync verified in mock environment.'],
        githubAuditRequirements: ['src/api.ts', 'src/errors.ts'],
      },
      {
        title: 'Package Exporters & Tests',
        description: 'Write CLI unit tests, package bundle, and compile binaries.',
        estimatedDays: 5,
        dependencies: ['REST API Sync Services'],
        acceptanceCriteria: ['All tests pass successfully', 'Bundled package runs natively on major operating systems'],
        deliverables: ['Compilation scripts', 'NPM release package files'],
        percentage: 20,
        releaseConditions: ['Release bundle verified.'],
        githubAuditRequirements: ['tests/cli.test.ts', 'package.json'],
      },
    ],
    tasks: [
      {
        title: 'Secure Local Config Storage',
        description: 'Develop file writing services that restrict read/write access using POSIX permissions.',
        estimatedHours: 6,
        priority: 'high',
        acceptanceCriteria: ['Local config files permissions verified'],
        githubAuditRequirements: ['src/config.ts'],
      },
    ],
    acceptanceCriteria: ['CLI tool parses flags', 'Config files persist securely'],
    dependencies: ['Node/Go environment', 'Remote staging API server'],
    riskAnalysis: [
      {
        description: 'Invalid user inputs causing CLI exit crashes.',
        severity: 'medium',
        mitigation: 'Implement globally captured try-catch error loggers.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 16,
      realisticDays: 20,
      conservativeDays: 28,
      summary: 'Requires approximately 3 weeks of engineering time across 4 milestones.',
    },
    deploymentStrategy: 'Compiled binaries packaged and published to NPM Registry.',
    testingStrategy: 'Unit tests using Jest/Vitest, CLI execution validation scripts.',
  },
  'web3_product': {
    executiveSummary: 'Predefined Web3 template featuring smart contract deployment, wallet integrations, decentralized events listeners, and dApp interfaces.',
    productVision: 'To offer a secure Web3 platform with auditable smart contracts and responsive dApp widgets.',
    functionalRequirements: [
      'Smart contract token transfer rules.',
      'Web3 wallet connector (MetaMask/Flint).',
      'Event listener transaction syncing.',
      'Decentralized metadata storage.',
    ],
    nonFunctionalRequirements: [
      'Audited smart contract bytecode.',
      'Immutable transaction records.',
      'Low gas/processing costs.',
    ],
    systemArchitecture: 'React frontend, Hardhat/Lucid smart contracts framework, ethers.js API connection.',
    databaseDesign: 'Smart contract state storage, indexed by ledger event block coordinates.',
    apiDesign: 'Contract RPC call mappings and transaction submit parameters.',
    milestones: [
      {
        title: 'Contract Design & HARDHAT',
        description: 'Develop Solidity/Plutus smart contracts and unit test suites.',
        estimatedDays: 5,
        dependencies: [],
        acceptanceCriteria: ['Contracts compile successfully', 'Unit tests verify token rules'],
        deliverables: ['Smart contract source files', 'Hardhat test files'],
        percentage: 25,
        releaseConditions: ['Contract compilation tests passing.'],
        githubAuditRequirements: ['contracts/Token.sol', 'test/token.test.js'],
      },
      {
        title: 'dApp Wallet Connections',
        description: 'Implement dApp pages, web3 context stores, and wallet connectors.',
        estimatedDays: 6,
        dependencies: ['Contract Design & HARDHAT'],
        acceptanceCriteria: ['App retrieves user wallet address', 'Connection switches network coordinates correctly'],
        deliverables: ['Wallet buttons components', 'Web3 provider providers'],
        percentage: 25,
        releaseConditions: ['Wallet connection verified on local blockchain.'],
        githubAuditRequirements: ['src/context/Web3Context.tsx', 'src/components/WalletConnect.tsx'],
      },
      {
        title: 'RPC APIs & Submissions',
        description: 'Code services submitting transactions and tracking block completions.',
        estimatedDays: 7,
        dependencies: ['dApp Wallet Connections'],
        acceptanceCriteria: ['API broadcasts transactions to nodes', 'UI displays transaction pending status'],
        deliverables: ['Transaction submitters', 'RPC client wrappers'],
        percentage: 30,
        releaseConditions: ['Block transactions execute successfully on local testnet.'],
        githubAuditRequirements: ['src/services/contract.ts', 'src/components/TransactionStatus.tsx'],
      },
      {
        title: 'Block Listeners & Audits',
        description: 'Write blockchain event logs indexers, and deploy to staging net.',
        estimatedDays: 6,
        dependencies: ['RPC APIs & Submissions'],
        acceptanceCriteria: ['Local database index matches block logs', 'Contract deploys to Testnet network'],
        deliverables: ['Event listener service', 'Staging deployment coordinates'],
        percentage: 20,
        releaseConditions: ['Staging smart contracts verified on explorer.'],
        githubAuditRequirements: ['src/services/listener.ts', 'scripts/deploy.js'],
      },
    ],
    tasks: [
      {
        title: 'Develop Smart Contract Lock',
        description: 'Write secure, non-reentrant contract functions restricting access rights.',
        estimatedHours: 12,
        priority: 'high',
        acceptanceCriteria: ['Re-entrancy tests run and fail to exploit contract'],
        githubAuditRequirements: ['contracts/Token.sol'],
      },
    ],
    acceptanceCriteria: ['Smart contract validates token rules', 'Web3 wallet executes transfers'],
    dependencies: ['Ethereum/Cardano local test node', 'RPC endpoint provider key'],
    riskAnalysis: [
      {
        description: 'Smart contract re-entrancy vulnerability.',
        severity: 'critical',
        mitigation: 'Incorporate OpenZeppelin ReentrancyGuard structures into Solidity contracts.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 20,
      realisticDays: 24,
      conservativeDays: 34,
      summary: 'Requires approximately 3.5 weeks of engineering time across 4 milestones.',
    },
    deploymentStrategy: 'Solidity contracts deployed to Sepolia Testnet, React UI on Vercel.',
    testingStrategy: 'Solidity coverage tools, re-entrancy attack simulation scripts.',
  },
  'startup_mvp': {
    executiveSummary: 'Predefined Startup MVP template including responsive landing page, basic signup database, simple product flow, and feedback collections.',
    productVision: 'To deliver a fast, validated MVP storefront verifying product market fit with minimal codebase complexities.',
    functionalRequirements: [
      'Modern responsive landing page.',
      'User signup waitlist database.',
      'Key customer workflow demo.',
      'Feedback collection submission forms.',
    ],
    nonFunctionalRequirements: [
      'Fast loading speeds (<1.5s).',
      'Ultra-simple database tables.',
      'Low monthly runtime costs.',
    ],
    systemArchitecture: 'HTML/Tailwind UI client, serverless Node.js handlers, MongoDB Atlas.',
    databaseDesign: 'Waitlist and Feedback collections stored in MongoDB database.',
    apiDesign: 'Endpoints including POST /waitlist/join, and POST /feedback/submit.',
    milestones: [
      {
        title: 'Landing Page & Layouts',
        description: 'Develop responsive landing page showing pricing details and waitlist signup form.',
        estimatedDays: 4,
        dependencies: [],
        acceptanceCriteria: ['Landing page renders on mobile/desktop', 'Waitlist form collects emails'],
        deliverables: ['HTML pages source code', 'Tailwind styling setups'],
        percentage: 25,
        releaseConditions: ['Landing page UI compiles without errors.'],
        githubAuditRequirements: ['public/index.html', 'src/styles.css'],
      },
      {
        title: 'Waitlist API & Data Store',
        description: 'Code serverless functions writing signups to MongoDB database.',
        estimatedDays: 4,
        dependencies: ['Landing Page & Layouts'],
        acceptanceCriteria: ['Valid emails save correctly', 'Duplicate email submissions rejected'],
        deliverables: ['Waitlist submit APIs', 'Mongoose database model'],
        percentage: 25,
        releaseConditions: ['Database endpoints pass unit tests.'],
        githubAuditRequirements: ['api/waitlist.ts', 'src/models/Waitlist.ts'],
      },
      {
        title: 'MVP Workflow Implementation',
        description: 'Implement core value proposition workflow (e.g. simple interactive app demo).',
        estimatedDays: 6,
        dependencies: ['Waitlist API & Data Store'],
        acceptanceCriteria: ['Demo workflow transitions views', 'User steps saved to sessions store'],
        deliverables: ['Core demo page components', 'Session states wrappers'],
        percentage: 30,
        releaseConditions: ['Demo features validated locally.'],
        githubAuditRequirements: ['src/components/DemoApp.tsx', 'src/store/demoSlice.ts'],
      },
      {
        title: 'Feedback Capture & Launch',
        description: 'Add feedback questionnaire forms, compile deploy bundles, and launch live staging.',
        estimatedDays: 4,
        dependencies: ['MVP Workflow Implementation'],
        acceptanceCriteria: ['Questionnaires persist inputs', 'Docker/Serverless container compiles'],
        deliverables: ['Staging deployment URL', 'Questionnaire components'],
        percentage: 20,
        releaseConditions: ['Staging deployment is live and working.'],
        githubAuditRequirements: ['api/feedback.ts', 'Dockerfile'],
      },
    ],
    tasks: [
      {
        title: 'Sanitize Waitlist Inputs',
        description: 'Write simple regex email validation check securing database.',
        estimatedHours: 4,
        priority: 'high',
        acceptanceCriteria: ['Invalid emails rejected on backend API'],
        githubAuditRequirements: ['api/waitlist.ts'],
      },
    ],
    acceptanceCriteria: ['Landing page registers emails', 'Interactive value demo functional'],
    dependencies: ['MongoDB Atlas database instance', 'Serverless deployment tools'],
    riskAnalysis: [
      {
        description: 'Spam email waitlist submissions.',
        severity: 'low',
        mitigation: 'Incorporate simple honeypot input check on waitlist signup forms.',
      },
    ],
    timelineEstimates: {
      optimisticDays: 14,
      realisticDays: 18,
      conservativeDays: 25,
      summary: 'Requires approximately 2.5 weeks of engineering time across 4 milestones.',
    },
    deploymentStrategy: 'Serverless functions and web client deployed to Vercel/Railway.',
    testingStrategy: 'Unit tests using Jest, user flow mock script verification.',
  },
};

export function getTemplatePlan(templateName: string, totalAmountPaise: number): NemotronProjectPlanInput {
  // Map templateName to keys
  let key = 'saas_app';
  const name = templateName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  if (name.includes('saas_app') || name.includes('saas') && !name.includes('ai')) {
    key = 'saas_app';
  } else if (name.includes('fintech')) {
    key = 'fintech_app';
  } else if (name.includes('ai_saas') || name.includes('ai')) {
    key = 'ai_saas';
  } else if (name.includes('marketplace')) {
    key = 'marketplace';
  } else if (name.includes('ecommerce') || name.includes('e_commerce')) {
    key = 'ecommerce_platform';
  } else if (name.includes('mobile')) {
    key = 'mobile_app';
  } else if (name.includes('crm')) {
    key = 'crm_system';
  } else if (name.includes('developer_tool') || name.includes('dev')) {
    key = 'developer_tool';
  } else if (name.includes('web3')) {
    key = 'web3_product';
  } else if (name.includes('mvp') || name.includes('startup')) {
    key = 'startup_mvp';
  }

  const base = templates[key] || templates['saas_app'];
  
  // Create complete NemotronProjectPlanInput with budgets adjusted dynamically to totalAmountPaise
  let sumAllocation = 0;
  const milestones = base.milestones.map((m, idx) => {
    const isLast = idx === base.milestones.length - 1;
    const allocation = isLast
      ? totalAmountPaise - sumAllocation
      : Math.floor(totalAmountPaise * (m.percentage / 100));
    sumAllocation += allocation;
    
    return {
      title: m.title,
      description: m.description,
      estimatedDays: m.estimatedDays,
      dependencies: m.dependencies,
      acceptanceCriteria: m.acceptanceCriteria,
      deliverables: m.deliverables,
      percentage: m.percentage,
      budgetAllocation: allocation,
      releaseConditions: m.releaseConditions,
      githubAuditRequirements: m.githubAuditRequirements,
    };
  });

  return {
    ...base,
    milestones,
  };
}
